### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Flashwalker** [sk1project/color-picker#8]
```
$ color-picker
TRASLATOR INIT
Traceback (most recent call last):
  File "/usr/bin/color-picker", line 22, in <module>
    cp2.run()
  File "/usr/lib/color-picker-1.0/cp2/__init__.py", line 68, in run
    from .app import ColorPickerApp
  File "/usr/lib/color-picker-1.0/cp2/app.py", line 25, in <module>
    from cp2.app_cms import AppColorManager
  File "/usr/lib/color-picker-1.0/cp2/app_cms.py", line 23, in <module>
    from uc2.cms import ColorManager, CS, libcms, val_255
  File "/usr/lib/color-picker-1.0/uc2/cms/__init__.py", line 21, in <module>
    from . import libcms
  File "/usr/lib/color-picker-1.0/uc2/cms/libcms.py", line 25, in <module>
    from . import _cms
ImportError: cannot import name '_cms' from partially initialized module 'uc2.cms' (most likely due to a circular import) (/usr/lib/color-picker-1.0/uc2/cms/__init__.py)

```

**Comment by sk1project** [comment]
Please report you distro and how you installed the app (package, source code etc.)

**Comment by Flashwalker** [comment]
I use Pop os - Ubuntu 20.04 x64. I downloaded `python3-color-picker-1.0_ubuntu_19.10_amd64.deb`.

**Comment by sk1project** [comment]
It seems package for ubuntu 19.10 is not compatible. We need to build ubuntu 20.04 package to resolve this issue. Hope this will be soon and we will let you know.

**Comment by sk1project** [comment]
@Flashwalker hope we have fixed this issue by including packages for Ubuntu 20.04, LinuxMint 20 and MX Linux 19 into daily build. You can fetch them on following link: 
https://sk1project.net/color-picker/daily-builds/ 
Please try it and let us know the result.

**Comment by Flashwalker** [comment]
unfortunately it fails too

**Comment by sk1project** [comment]
@Flashwalker This looks like clashes in python evn versions. We have fixed this issue in latest build:

https://downloads.sk1project.net/color-picker/nightbuilds/Ubuntu/python3-sk1-color-picker-1.1rc_20210118_ubuntu_20.04_amd64.deb

The package has been tested under Ubuntu 20.04, so it should work definitely. Please note that application launcher is `sk1-color-picker` now.
